### ISSUE TITLE
Issue with notebook ...

### ISSUE THREAD

**Issue by mmcky** [jstac/econometrics#4]
`notebooks/Chapter_10/nikkei_returns_data.ipynb#`

Needs an update for `header=True`

**Comment by mmcky** [comment]
`notebooks/Chapter_12/multicollinearity_and_precision.ipynb#`

Issue with dvipng

**Comment by jstac** [comment]
@mmcky Many thanks.  Do you need me to do something?

**Comment by mmcky** [comment]
@jstac Just opened this issue to track the notebooks. Chapter10 was an easy fix. Just recompiling the image now to see if Chapter12 is fixed.
